networks:
  app:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.100.0/24

services:

  nginx.app:
    build:
      context: ./
      dockerfile: nginx.dockerfile
    image: nginx.app
    container_name: nginx.app
    depends_on:
      app.app:
        condition: service_started
    volumes:
      - "./nginx/app_conf:/etc/nginx/conf.d/"
      - "./code/phpinfo:/var/www/html/phpinfo"
      - "./code/app:/var/www/html/app"
      - "/etc/letsencrypt/:/etc/letsencrypt/"
      - "./logs/nginx:/var/log/nginx"
    networks:
      app:
        ipv4_address: 172.16.100.202
    ports:
      - "80"
      - "443"

  image.app:
    build:
      context: ./
      dockerfile: php8.3-fpm.dockerfile
    image: image.app
    container_name: image.app
    networks:
      app:
        ipv4_address: 172.16.100.100
    ports:
      - "9000"

  app.app:
    image: app.app
    container_name: app.app
    depends_on:
      mariadb.app:
        # This ensures phpMyAdmin starts only after the 'mariadb' container is running
        # If using healthchecks, you could do: condition: service_healthy
        condition: service_started 
    volumes:
      - "./code/phpinfo:/var/www/html/phpinfo"
      - "./code/app:/var/www/html/app"
      - "./php_ini/php.ini:/usr/local/etc/php/php.ini"
      - "./logs/php:/var/log/php"
    networks:
      app:
        ipv4_address: 172.16.100.101
    ports:
      - "9000"

  mariadb.app:
    image: mariadb:latest
    container_name: mariadb.app
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_INITDB_SKIP_TZINFO: "yes"
      MYSQLD_ARGS: "--bind-address=0.0.0.0"
#      MYSQLD_ARGS: "--bind-address=0.0.0.0, --sql_mode='NO_ENGINE_SUBSTITUTION'"
    networks:
      app:
        ipv4_address: 172.16.100.102
    volumes:
      - "./logs/mariadb:/var/log/mariadb"
      - "./mariadb/data:/var/lib/mysql"
    ports:
      - "3306"

  phpmyadmin.app:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin.app
    environment:
      PMA_HOST: mariadb.app
      PMA_PASSWORD: password
    depends_on:
      mariadb.app:
        # This ensures phpMyAdmin starts only after the 'mariadb' container is running
        # If using healthchecks, you could do: condition: service_healthy
        condition: service_started    
    networks:
      app:
        ipv4_address: 172.16.100.103
    ports:
      - "80"
